package pojo;
// Generated Oct 24, 2020 8:58:13 PM by Hibernate Tools 3.6.0


import dao.Dao;
import java.util.List;
import javax.faces.bean.ManagedBean;
/**
 * DataTable generated by hbm2java
 */
@ManagedBean
public class DataTable  implements java.io.Serializable {


     private Integer userId;
     private String userAlamat;
     private String type;
     private String amount;
     private String date;

    public DataTable() {
    }

    public DataTable(String userAlamat, String type, String amount, String date) {
       this.userAlamat = userAlamat;
       this.type = type;
       this.amount = amount;
       this.date = date;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserAlamat() {
        return this.userAlamat;
    }
    
    public void setUserAlamat(String userAlamat) {
        this.userAlamat = userAlamat;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }

    public void save()
    {
        Dao pdao=new Dao();
        pdao.addDataTable(this);
    }

    public void delete()
    {    
        Dao pdao=new Dao();
        pdao.deleteDataTable(userId);
    }

    public List<DataTable> getbyid()
    { 
        Dao pdao=new Dao();
        List<DataTable> prod=pdao.getbyID(userId);
        userAlamat=prod.get(0).userAlamat;
        type=prod.get(0).type;
        amount=prod.get(0).amount;
        date=prod.get(0).date;
        return prod;
    }

    public List<DataTable> getallrecords()
    {
        Dao pdao=new Dao();
        List<DataTable> prod=pdao.retrieveDataTable();
        return prod;
    }

    public void update()
    {
        Dao pdao=new Dao();
        pdao.updateDataTable(this);
    }


}


