package pojo;
// Generated Oct 24, 2020 8:58:13 PM by Hibernate Tools 3.6.0

import dao.DaoMsgtbl;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;





/**
 * MessageTable generated by hbm2java
 */
@ManagedBean
public class MessageTable  implements java.io.Serializable {


     private Integer msgId;
     private int userId;
     private String msg;

    public MessageTable() {
    }

    public MessageTable(int userId, String msg) {
       this.userId = userId;
       this.msg = msg;
    }
   
    public Integer getMsgId() {
        return this.msgId;
    }
    
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }

    public void save()
    {
        DaoMsgtbl pdao=new DaoMsgtbl();
        pdao.addMessageTable(this);
    }

    public void delete()
    {    
        DaoMsgtbl pdao=new DaoMsgtbl();
        pdao.deleteMessageTable(msgId);
    }

    public List<MessageTable> getbyid()
    { 
        DaoMsgtbl pdao=new DaoMsgtbl();
        List<MessageTable> prod=pdao.getbyID(msgId);
        userId=prod.get(0).userId;
        msg=prod.get(0).msg;
        return prod;
    }

    public List<MessageTable> getallrecords()
    {
        DaoMsgtbl pdao=new DaoMsgtbl();
        List<MessageTable> prod=pdao.retrieveMessageTable();
        return prod;
    }

    public void update()
    {
        DaoMsgtbl pdao=new DaoMsgtbl();
        pdao.updateMessageTable(this);
    }


}
