package pojo;
// Generated Oct 24, 2020 8:58:13 PM by Hibernate Tools 3.6.0

import dao.DaoOrdertbl;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;




/**
 * OrderTable generated by hbm2java
 */
@ManagedBean
public class OrderTable  implements java.io.Serializable {


     private Integer orderId;
     private String amount;
     private String type;
     private int price;

    public OrderTable() {
    }

    public OrderTable(String amount, String type, int price) {
       this.amount = amount;
       this.type = type;
       this.price = price;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }

    public void save()
    {
        DaoOrdertbl pdao=new DaoOrdertbl();
        pdao.addOrderTable(this);
    }

    public void delete()
    {    
        DaoOrdertbl pdao=new DaoOrdertbl();
        pdao.deleteOrderTable(orderId);
    }

    public List<OrderTable> getbyid()
    { 
        DaoOrdertbl pdao=new DaoOrdertbl();
        List<OrderTable> prod=pdao.getbyID(orderId);
        amount=prod.get(0).amount;
        type=prod.get(0).type;
        price=prod.get(0).price;
        return prod;
    }

    public List<OrderTable> getallrecords()
    {
        DaoOrdertbl pdao=new DaoOrdertbl();
        List<OrderTable> prod=pdao.retrieveOrderTable();
        return prod;
    }

    public void update()
    {
        DaoOrdertbl pdao=new DaoOrdertbl();
        pdao.updateOrderTable(this);
    }


}


