package pojo;
// Generated Oct 24, 2020 8:58:13 PM by Hibernate Tools 3.6.0


import dao.DaoPaymenttbl;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;

/**
 * PaymentTable generated by hbm2java
 */
@ManagedBean
public class PaymentTable  implements java.io.Serializable {


     private Integer userId;
     private int orderId;
     private int price;
     private String date;

    public PaymentTable() {
    }

    public PaymentTable(int orderId, int price, String date) {
       this.orderId = orderId;
       this.price = price;
       this.date = date;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }

    public void save()
    {
        DaoPaymenttbl pdao=new DaoPaymenttbl();
        pdao.addPaymentTable(this);
    }

    public void delete()
    {    
        DaoPaymenttbl pdao=new DaoPaymenttbl();
        pdao.deletePaymentTable(userId);
    }

    public List<PaymentTable> getbyid()
    { 
        DaoPaymenttbl pdao=new DaoPaymenttbl();
        List<PaymentTable> prod=pdao.getbyID(userId);
        orderId=prod.get(0).orderId;
        price=prod.get(0).price;
        date=prod.get(0).date;
        return prod;
    }

    public List<PaymentTable> getallrecords()
    {
        DaoPaymenttbl pdao=new DaoPaymenttbl();
        List<PaymentTable> prod=pdao.retrievePaymentTable();
        return prod;
    }

    public void update()
    {
        DaoPaymenttbl pdao=new DaoPaymenttbl();
        pdao.updatePaymentTable(this);
    }


}


