package pojo;
// Generated Oct 24, 2020 8:58:13 PM by Hibernate Tools 3.6.0

import dao.DaoUsertbl;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;




/**
 * UserTable generated by hbm2java
 */
@ManagedBean
public class UserTable  implements java.io.Serializable {


     private Integer userId;
     private int userLogin;
     private int userPassword;
     private String userAlamat;
     private String userEmail;

    public UserTable() {
    }

    public UserTable(int userLogin, int userPassword, String userAlamat, String userEmail) {
       this.userLogin = userLogin;
       this.userPassword = userPassword;
       this.userAlamat = userAlamat;
       this.userEmail = userEmail;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public int getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(int userLogin) {
        this.userLogin = userLogin;
    }
    public int getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(int userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserAlamat() {
        return this.userAlamat;
    }
    
    public void setUserAlamat(String userAlamat) {
        this.userAlamat = userAlamat;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public void save()
    {
        DaoUsertbl pdao=new DaoUsertbl();
        pdao.addUserTable(this);
    }

    public void delete()
    {    
        DaoUsertbl pdao=new DaoUsertbl();
        pdao.deleteUserTable(userLogin);
    }

    public List<UserTable> getbyid()
    { 
        DaoUsertbl pdao=new DaoUsertbl();
        List<UserTable> prod=pdao.getbyID(userLogin);
        userPassword=prod.get(0).userPassword;
        userAlamat=prod.get(0).userAlamat;
        userEmail=prod.get(0).userEmail;
        return prod;
    }

    public List<UserTable> getallrecords()
    {
        DaoUsertbl pdao=new DaoUsertbl();
        List<UserTable> prod=pdao.retrieveUserTable();
        return prod;
    }

    public void update()
    {
        DaoUsertbl pdao=new DaoUsertbl();
        pdao.updateUserTable(this);
    }


}


